### ISSUE TITLE
Unable to launch application

### ISSUE THREAD

**Issue by lukeaus** [khornberg/docker-indicator#3]
On El Capitan docker-indicator is failing to launch.

Console gives this error message
21/12/2015 19:33:05.711 lsd[285]: LaunchServices: Could not store lsd-identifiers file at /private/var/db/lsd/com.apple.lsdschemes.plist

**Comment by khornberg** [comment]
Bummer. You may want to try the solution [here](https://github.com/Microsoft/vscode/issues/92).

I don't have El Capitan installed currently. I'll keep this in mind when I install it.

**Comment by lukeaus** [comment]
I do not have visual studio code installed.

Turns out I had a typo in the configuration file name and was only sporadically getting another warning telling me the file was missing. I saw the error once and accidentally closed it, then it did not come back again till I deleted docker-indicator and com.electron.docker-indicator.plist

Feel free to close this 'issue'.

**Comment by khornberg** [comment]
Ok. Does it work now?

Kyle

**Comment by lukeaus** [comment]
Yes - all working as expected.
Thanks Kyle

**Comment by khornberg** [comment]
Good to hear

Kyle
